package pe.dcs.app.features.notification.domain;

/**
 * Tipos de aviso del sistema. Todo aviso pasa por {@code NotificationService}; el texto de cada tipo vive en el diccionario del
 * front (inbox.types.TIPO.title / .body) y se rellena con los parámetros. Los TRANSACTIONAL no se pueden desactivar (V16).
 */
public enum NotificationType {
    SUPPORT_NEW_CASE(Category.TRANSACTIONAL),
    SUPPORT_ORG_REPLY(Category.TRANSACTIONAL),
    SUPPORT_STAFF_REPLY(Category.TRANSACTIONAL),
    SUPPORT_ASSIGNED(Category.TRANSACTIONAL),
    SUPPORT_RESOLVED(Category.TRANSACTIONAL),
    SUPPORT_CLOSED(Category.TRANSACTIONAL),
    SUPPORT_AUTO_CLOSED(Category.TRANSACTIONAL),
    SUPPORT_SLA_BREACH(Category.TRANSACTIONAL),
    CONTRACT_EXPIRING(Category.TRANSACTIONAL),
    VISITOR_NEW(Category.TRANSACTIONAL),
    VISITOR_ASSIGNED(Category.TRANSACTIONAL),
    VISITOR_SLA_BREACH(Category.TRANSACTIONAL),
    ATTENDANCE_ABSENCE(Category.TRANSACTIONAL),
    TRANSFER_REQUESTED(Category.TRANSACTIONAL),
    TRANSFER_APPROVED(Category.TRANSACTIONAL),
    TRANSFER_REJECTED(Category.TRANSACTIONAL),
    TRANSFER_EXPIRED(Category.TRANSACTIONAL),
    TRANSFER_ORIGIN(Category.TRANSACTIONAL),
    TRANSFER_EXECUTED(Category.TRANSACTIONAL),
    VISIBILITY_REQUESTED(Category.TRANSACTIONAL),
    VISIBILITY_APPROVED(Category.TRANSACTIONAL),
    VISIBILITY_REJECTED(Category.TRANSACTIONAL),
    VISIBILITY_EXPIRED(Category.TRANSACTIONAL),
    VISIBILITY_REVOKED(Category.TRANSACTIONAL),
    GROUP_JOIN_REQUESTED(Category.TRANSACTIONAL),
    GROUP_JOIN_APPROVED(Category.TRANSACTIONAL),
    GROUP_JOIN_REJECTED(Category.TRANSACTIONAL),
    GROUP_LEADER_ASSIGNED(Category.TRANSACTIONAL),
    MINISTRY_JOIN_REQUESTED(Category.TRANSACTIONAL),
    MINISTRY_JOIN_APPROVED(Category.TRANSACTIONAL),
    MINISTRY_JOIN_REJECTED(Category.TRANSACTIONAL),
    MINISTRY_ASSIGNED(Category.TRANSACTIONAL),
    MINISTRY_LEADER_ASSIGNED(Category.TRANSACTIONAL),
    MINISTRY_SCREENING_EXPIRED(Category.TRANSACTIONAL),
    SHIFT_ASSIGNED(Category.TRANSACTIONAL),
    SHIFT_DECLINED(Category.TRANSACTIONAL),
    SHIFT_REMINDER(Category.TRANSACTIONAL),
    RITE_MEMBERSHIP_REQUESTED(Category.TRANSACTIONAL),
    RITE_MEMBERSHIP_APPROVED(Category.TRANSACTIONAL),
    RITE_MEMBERSHIP_REJECTED(Category.TRANSACTIONAL),
    RITE_BAPTISM_REQUESTED(Category.TRANSACTIONAL),
    RITE_BAPTISM_APPROVED(Category.TRANSACTIONAL),
    RITE_BAPTISM_REJECTED(Category.TRANSACTIONAL),
    RITE_MARRIAGE_REQUESTED(Category.TRANSACTIONAL),
    RITE_MARRIAGE_APPROVED(Category.TRANSACTIONAL),
    RITE_MARRIAGE_REJECTED(Category.TRANSACTIONAL),
    RITE_DEDICATION_REQUESTED(Category.TRANSACTIONAL),
    RITE_DEDICATION_APPROVED(Category.TRANSACTIONAL),
    RITE_DEDICATION_REJECTED(Category.TRANSACTIONAL),
    APPROVAL_COMMENT(Category.TRANSACTIONAL),
    APPROVAL_INFO(Category.TRANSACTIONAL),
    APPROVAL_REMINDER(Category.TRANSACTIONAL),
    PASTORAL_CASE_ASSIGNED(Category.PASTORAL),
    PASTORAL_CASE_OPENED(Category.PASTORAL),
    PASTORAL_SLA_WARNING(Category.PASTORAL),
    PASTORAL_ESCALATED(Category.PASTORAL),
    TRAINING_CLASS_CANCELLED(Category.TRANSACTIONAL),
    TRAINING_ENROLLMENT_RESULT(Category.TRANSACTIONAL),
    TRAINING_CERTIFICATE_ISSUED(Category.TRANSACTIONAL),
    EVENT_CANCELLED(Category.EVENTS),
    EVENT_WAITLIST_PROMOTED(Category.EVENTS),
    EVENT_PAYMENT_CONFIRMED(Category.EVENTS),
    EVENT_REGISTRATION_CONFIRMED(Category.EVENTS),
    FINANCE_MOVEMENT_APPROVED(Category.FINANCE),
    FINANCE_MOVEMENT_REJECTED(Category.FINANCE),
    FINANCE_MOVEMENT_VOIDED(Category.FINANCE),
    FINANCE_BUDGET_OVERSPEND(Category.FINANCE),
    FINANCE_PERIOD_CLOSED(Category.FINANCE),
    FINANCE_PERIOD_REOPENED(Category.FINANCE),
    SPACE_RESERVATION_REQUESTED(Category.TRANSACTIONAL),
    SPACE_RESERVATION_APPROVED(Category.TRANSACTIONAL),
    SPACE_RESERVATION_REJECTED(Category.TRANSACTIONAL),
    INVENTORY_LOW_STOCK(Category.TRANSACTIONAL),
    INVENTORY_ASSIGNMENT_OVERDUE(Category.TRANSACTIONAL),
    LEAVE_REQUEST_REQUESTED(Category.TRANSACTIONAL),
    LEAVE_REQUEST_APPROVED(Category.TRANSACTIONAL),
    LEAVE_REQUEST_REJECTED(Category.TRANSACTIONAL),
    REPORT_SCHEDULED_READY(Category.TRANSACTIONAL),
    REPORT_SCHEDULED_SKIPPED(Category.TRANSACTIONAL),
    PORTAL_SIGNUP_REQUESTED(Category.TRANSACTIONAL),
    PORTAL_SIGNUP_APPROVED(Category.TRANSACTIONAL),
    PORTAL_SIGNUP_REJECTED(Category.TRANSACTIONAL),
    PORTAL_SIGNUP_EXPIRED(Category.TRANSACTIONAL);

    public enum Category { TRANSACTIONAL, COMMUNITY, EVENTS, FINANCE, PASTORAL }

    private final Category category;

    NotificationType(Category category) {
        this.category = category;
    }

    public Category category() {
        return category;
    }
}
