server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/RJ_DoxApp_v1
    username: postgres
    password: Clannad

    hikari:
      auto-commit: false
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000


  main:
    web-application-type: servlet

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        show_sql: true
        jdbc:
          prepare_sql: false
          time_zone: UTC
        connection:
          provider_disables_autocommit: true

supabase:
  url: https://eehevpofwzkhmfetldyz.supabase.co
  serviceKey: sb_secret_ECnwK-OqYyF0OlN-stFnrw_mhgWX9SF

  storage:
    buckets:
      events: events

app:
  jwt:
    time-in-minutes: 20
    secret: r3g157ry_499l1c4t10n_574nd4rd_cl13n7_53cr37