package pe.dcs.app.features.auth.domain;

public enum LoginResult {
    SUCCESS, BAD_PASSWORD, UNKNOWN_USER, LOCKED, INACTIVE, RATE_LIMITED, MFA_FAILED, MFA_REQUIRED,
    ORG_BLOCKED, NO_ACCESS, REFRESH_REUSE, PASSWORD_RESET, PASSWORD_CHANGED, INVITE_ACCEPTED
}
